site_name: Robot Day
site_description: 'Robot Day is content for hosting a robotics event at your organization. All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/GITHUB_REPO_NAME'
repo_url: 'https://github.com/dmccreary/GITHUB_REPO_NAME'

nav:
  - Home: index.md
  - About: about.md
  - Process: process.md
  - Concepts: concepts.md
  - Tables: tables.md
  - Activities:
        - activities/index.md
        - activities/batteries.md
        - activities/code.md
        - activities/computer-vision.md
        - activities/displays.md
        - activities/donkey-car.md
        - activities/h-bridge.md
        - activities/motors.md
        - activities/pwm.md
        - activities/sensors.md
  - Contact: contact.md
 
# CoderDojo Microsite Standards from here down
edit_uri: 'blob/master/docs'
theme:
  name: material
  extra_css:
    - styles/custom.css
  # logo: img/my-icon.png
  # favicon: img/my-icon.png
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
plugins:
  - search
#  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
extra:
  analytics:
    provider: google
    property: G-9X7Q8719QV