site_name: Robot Day
site_description: 'Robot Day is content for hosting a robotics event at your organization. All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'robot-day'
site_url: 'https://dmccreary.github.io/robot-day'
repo_url: 'https://github.com/dmccreary/robot-day'

nav:
  - Robot Day Home: index.md
  - About: about.md
  - Process: process.md
  - Personas: personas.md
  - Concepts: concepts.md
  - Tables: tables.md
  - Activities:
    - Introduction: activities/index.md
    - Batteries: activities/batteries.md
    - Battery Testing: activities/battery-test.md
    - Battery Recharging: activities/battery-recharging.md
    - Breadboard: activities/breadboard.md
    - LEDs: activities/led.md
    - RGB LEDs: activities/led-rgb.md
    - Microswitch: activities/microswitch.md
    - Electronics Starter Kit: activities/electronics-starter-kit.md
    - Motors: activities/motors.md
    - H-Bridge: activities/h-bridge.md
    - Pulse Width: activities/pwm.md
    - RGB Box: activities/rgb-box.md
    - Moving Rainbow: activities/moving-rainbow.md
    - Sensors: activities/sensors.md
    - Potentiometers: activities/pot-lab.md
    - Time of Flight: activities/time-of-flight.md
    - Displays: activities/displays.md
    - Microcontrollers: activities/microcontrollers.md
    - Code: activities/code.md
    - Computer Vision: activities/computer-vision.md
    - Robot: activities/robot.md
    - Donkey Car: activities/donkey-car.md
  - Discussions and Lesson Plans:
    - Introduction: lessons/index.md
    - Generate Lessons: lessons/01-generate-lesson-plans.md
    - Batteries:
      - 5th Grade Discussion: lessons/batteries-5th-grade.md
      - 9th Grade Lesson Plan: lessons/batteries-9th-grade.md
      - 11th Grade Discussion: lessons/batteries-11th-grade.md
    - Displays:
      - NeoPixels: lessons/neopixel.md
  - Promoting Robot Day: promoting.md
  - Topic Lists: topic-list.md
  - Parts and Kits: kits.md
  - Scaling: scaling.md
  - Glossary of Terms: glossary.md
  - License: license.md
  - Contact: contact.md


# CoderDojo Microsite Standards from here down
edit_uri: 'blob/master/docs'
theme:
  name: material
  extra_css:
    - styles/custom.css
  logo: img/logo.png
  favicon: img/favicon.ico
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
plugins:
  - search
  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
extra:
  analytics:
    provider: google
    property: G-9X7Q8719QV